### PR TITLE
Simplify surt creation route logic

### LINKED ISSUE #8: Default output (without a custom providedURIR) does not generate SURTs with ) host and path separator
Via @ibnesayeed in #4

### PR DESCRIPTION
**Pull request by machawk1**
Closes #8 

@ibnesayeed, can you review this? I cannot yet add you as a reviewer on this repo yet.

### CODE REVIEW

**Comment by machawk1** [comment]
For some reason this subtle change breaks the randomization.

**Comment by machawk1** [comment]
This is caused by writing to the variable of the arg passed in.

Adding:
```
foo = provided_urir
```
and changing to
```
surted_urir = surt.surt(
  foo,
  path_strip_trailing_slash_unless_empty=True)
```
prevents this bug from occuring.

**Comment by ibnesayeed** [comment]
Since you are already using `faker`, why don't you use something like `fake.uri()` instead of cooking up a URI yourself? This will simplify the process a lot. Also, I am not sure what is the pressing need of `provided_urir` here, which is causing unnecessary code branching.

**Comment by machawk1** [comment]
The variety from faker for URI generation seems a little more limited than the process implemented, e.g., https://github.com/joke2k/faker/blob/ced876f8dfd951c4e6fdbc7188f222bac1b235b2/faker/providers/internet/__init__.py's selection of TLDs.

`provided_uri` here is the value provided from the user. The logic in question is for the scenario where it is not provided, i.e., for generation. Can you provide an alternate to this, @ibnesayeed?

**Comment by ibnesayeed** [comment]
> The variety from faker for URI generation seems a little more limited than the process implemented, e.g., https://github.com/joke2k/faker/blob/ced876f8dfd951c4e6fdbc7188f222bac1b235b2/faker/providers/internet/__init__.py's selection of TLDs.

Their URIs are way more versatile despite having a shorter set of TLDs. They do cover most common TLDs. You might miss international domain names, but you will get URIs with more structures like varying schemes, paths and file extensions. You can even make it give you domain names of varying number of segments. All these things are missing from your current implementation.

> `provided_uri` here is the value provided from the user. The logic in question is for the scenario where it is not provided, i.e., for generation. Can you provide an alternate to this, @ibnesayeed?

I know what it does, but why would we ever ask a user to provide a URI-R in the first place and repeatedly generate CDXJ records for the same URI? I think we can simply remove this option unless there is a compelling need to keep it.

**Comment by machawk1** [comment]
> would we ever ask a user to provide a URI-R in the first place and repeatedly generate CDXJ records for the same URI

For testing. I have specifically used this feature.

I will consider the move to use faker's `uri()`.

Thanks, @ibnesayeed!

**Pull request merged**
